### ISSUE TITLE
Pyautogui.typewrite() not typing #

### ISSUE THREAD

**Issue by DylanMcBean** [asweigart/pyautogui#259]
![image](https://user-images.githubusercontent.com/40377397/44623504-23105a80-a8c8-11e8-9884-c3ce88841e05.png)
the pyautogui.typewrite() doesn't want to print # it prints ~. my keyboard is on the us layout.. any help??

**Comment by vbhv007** [comment]
It works fine for me. I'm using Linux Mint 18.3 with US layout. Can you specify your OS?

**Comment by DylanMcBean** [comment]
Windows 10

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mikebvansickle** [comment]
@DylanMcBean I'm having no issues with this with the following:
- Windows 10 / US Keyboard layout
- Python 3.7.1
- pyautogui

I tested it from within the command prompt as well as a simple script that clicks into a word document and writes the requested text.. Not sure why you're getting tilde outputs.

If you are using the Canadian French keyboard: 
![image](https://user-images.githubusercontent.com/42155126/48081435-0cd32480-e1be-11e8-995c-deaed69ea2b3.png)

There may be some interaction there as the Canadian French "#" input is where the "~" input is on the US keyboard layout, however, it doesn't really make sense due to the fact that the caret (^) correctly printed. Hope you found a solution, my comment is a bit late.

**Comment by DylanMcBean** [comment]
The keyboard I am using is the Razor Blackwidow Chroma 2, this is the layout that I have[cid:image003.png@01D476A2.146B1A90]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by i-need-to-tell-you-something** [comment]
@DylanMcBean Can't see the attached layout.

**Comment by setvisible** [comment]
Hello!

Here a workaround:

```python
import pyautogui
import pyperclip

def _workaround_write(text):
    """
    This is a work-around for the bug in pyautogui.write() with non-QWERTY keyboards
    It copies the text to clipboard and pastes it, instead of typing it.
    """
    pyperclip.copy(text)
    pyautogui.hotkey('ctrl', 'v')
    pyperclip.copy('')

# Test
text_with_special_chars = '@/:;\\.ABCabc?!~^[]{}()'
pyautogui.write(text_with_special_chars) 
# >>> //;\.ABCabc?§¨[]5°      -> NOK

_workaround_write(text_with_special_chars) 
# >>> @/:;\.ABCabc?!~^[]{}()       -> OK :)
```
It solved the issue on my Windows 64-bits machine / AZERTY french keyboard

**Comment by tpchuckles** [comment]
I wouldn't call this workaround a "fix", and i think the issue boils down to the distinction between keypresses and the sending of a character.

for example, I'm trying to put together an onscreen greek character keyboard, but there is no key if i try to pyautogui.write("μ")

also, ctrl+v also might give undesired effects depending on where we're trying to paste (e.g. pasting into the terminal). i eventually resorted to a rightClick(), press("down") (x3, just because "Paste" is the 3rd option down in that specific right-click menu), press("enter"). this does the job, but good god, gross. and super fragile.
