### ISSUE TITLE
Locate Function cannot work and even can not return none

### ISSUE THREAD

**Issue by ripperchan** [asweigart/pyautogui#294]
<img width="746" alt="problem" src="https://user-images.githubusercontent.com/29171777/51294080-52c52800-1a4c-11e9-90ee-4841d43c8db8.PNG">
As the attachment, the locate function on my computer is not working.
And i'm sure the syntax and the picture are correct.
Anyone meets the same problem?

**Comment by tuffknitz** [comment]
I've been banging my head against the wall over this since yesterday - so I'm pleased (?) that someone else is experiencing the same thing.  I'm using the latest version of pyautogui and Python 3.7. My test code:

```
img = None
while img is None:
  img = pyautogui.locateOnScreen('images/Menu.PNG', confidence=0.8, grayscale = True)
print('found!')
```
![image](https://user-images.githubusercontent.com/16940592/51356496-88c7d380-1a6f-11e9-972c-f050b3d4edc7.png)

**Comment by asweigart** [comment]
This has been in update in the 0.9.41, where not finding an image results in raising an exception instead of returning None. The reasoning behind this best practice is here: https://medium.com/@wbrucek/effective-python-practice-problem-dont-return-none-from-a-function-2d31f37b2ce7

The solution for your problem is to use a try/except statement instead of checking the return value for None.
