### ISSUE TITLE
typewrite() writes to shell instead of clicked input/document

### ISSUE THREAD

**Issue by wyatt-troia** [asweigart/pyautogui#365]
I am following [Chapter 18 of Automate the Boring Stuff with Python](https://automatetheboringstuff.com/chapter18/#calibre_link-3667). I'm on OS X and `pyautogui` 0.9.47.

I am trying to use `pyautogui` to click on a text input or text document and then input text.

I am entering the following into a shell (`(370, 80)` are the coordinates of my Chrome address bar):

`pyautogui.click(370,80); pyautogui.typewrite('Hello world!')`

`click()` seems to not be working as expected. It will highlight text in an input when I click on the input, but even when I manually type after the click, the text shows up in the shell. See [this screenshot](https://imgur.com/3EF0dBA) of the result of running the above line.

Other methods like `position()`, `moveTo()`, `moveRel()`, and `dragTo()` are working as expected. Pausing before `typewrite()` (as in `pyautogui.click(370,80); time.sleep(3); pyautogui.typewrite('Hello world!')`) doesn't fix it.

If I run `time.sleep(5); pyautogui.typewrite('test')` and manually click on the text document or input while the thread is sleeping, the text is inputted as desired.

What might be the problem? I've had the same issue on both Macs I've tested on.

**Comment by jordanmcleod** [comment]
The solution you stated works in Win7 with Firefox and Vivaldi; altered x-y to suit my screen.

Do you get a different result if you instead use `pyautogui.moveTo(370,80); pyautogui.click(); pyautogui.typewrite('Hello world!')`?

**Comment by wyatt-troia** [comment]
@jordanmcleod Unfortunately I get the same result as before.

**Comment by wyatt-troia** [comment]
@jordanmcleod If I click on a text input with pyautogui and then try to manually type, the characters still appear in the shell, so it seems like click() isn't working correctly.

**Comment by jordanmcleod** [comment]
@wyatt-troia There's a PR (https://github.com/asweigart/pyautogui/pull/358) related to "click()" specifically for OSX.  The source I have is version 0.9.47 which does not reflect this change (https://github.com/asweigart/pyautogui/pull/358/files).  If you're comfortable making this edit to your local file, you can determine if that fixes your issue.

Assuming your directory structure for python on OSX is the same as mine in Windows:
1) Open the "...\Python3x\Lib\site-packages\pyautogui\__init__.py" file with IDLE.
2) Press "Alt+G" to access the "Goto" pop-up.
3) In the "Go to line number" field, enter "510".
4) Click on "OK".
5) Verify the cursor is flashing at the beginning of "Ln: 510" as indicated in the lower right-hand corner of IDLE.
6) Change the "3" in "platformModule._multiClick(x, y, button, 3)" to "clicks" (without quotes).
7) Press "Ctrl+S" to save the file.
8) Attempt to run your program again.

If this doesn't fix the issue you're encountering, I'm out of ideas for pyautogui since I don't have an Apple on which to reproduce this.  In the source, the "win32api" for OSX appears to be "Quartz", so you could try using that to control the mouse directly.  Otherwise, I also found a few possible alternatives to pyautogui: pynput (https://pypi.org/project/pynput/); PyUserInput (https://github.com/PyUserInput/PyUserInput/issues).  I haven't used either of these, so I can't speak to their functionality.

**Comment by wyatt-troia** [comment]
@jordanmcleod That fixed it. Thank you!
