### ISSUE TITLE
incorrect shift-key sequences in __init__.py

### ISSUE THREAD

**Issue by jarviscodes** [asweigart/pyautogui#396]
### Pre:
On a Belgian AZERTY keyboard, keys like `! $ & < : ; ( )` are non-shift keys. 

### Problem:
```
In [1]: import pyautogui

In [2]: pyautogui.write('"')

In [3]: 3
```

3 would be the result with a shift key pressed.

### Expected:
```
...
in[3]: "
```

### Cause:

`__init__.py`'s `isShiftCharacter()` checks if the characters are in a hardcoded string: 

```
return character.isupper() or character in '~!@#$%^&*()_+{}|:"<>?'
```

### Solution:
Starting from the original keys (I haven't checked keys that aren't in the string), this would be a better set of Shift-enabled keys for Belgian AZERTY: `~@#%^*_+{}|>?`

Allthough it would be cleaner if we could somehow test the current keyboard layout and set the string of shift-characters that way.

**Comment by i-need-to-tell-you-something** [comment]
This problem is already mentioned in issue #137 . For a temporary workaround you can see there if @Iomira's solution helps you.

**Comment by jlintusaari** [comment]
Indeed, currently it is impossible to type some of these hard coded shift keys when they are not shift keys on non-US keyboard (because shift is always applied!). If you don't want to / can't change OS keyboard layout one currently working workaround is to overwrite `pyautogui.isShiftCharacter()`. For instance `<` and `+` are non shift characters in a Finnish keyboard, so by removing them from `pyautogui.isShiftCharacter()` you can actually write them:

```
import pyautogui

# Produces incorrectly the shift alternatives of these keys on a Finnish keyboard
pyautogui.write('<+')
# >?

# Modified version where the non-shift characters are removed
def isShiftCharacter(character):
    """Returns True if the key character is uppercase or shifted."""
    return character.isupper() or character in '~!@#$%^&*()_{}|:">?'

pyautogui.isShiftCharacter = isShiftCharacter

# Now this works
pyautogui.write('<+')
# <+
```

**Comment by xWhiteListed** [comment]
I appearantly missed #137 during my search. 

As a "clean" solution without translation or workarounds, it might be possible to implement keyboard layout checking per [this](https://stackoverflow.com/questions/42047253/how-to-detect-current-keyboard-language-in-python) confirmed SO answer.

Next, we can build up a dictionary of shift-character strings like:

```
shift_map_dict = { 
    'nl-be': '~@#%^*_+{}|>?',
    'en-us': '~!@#$%^&*()_{}|:">?'
}
```

This way, finally we could turn:

```
def isShiftCharacter(character):
    """Returns True if the key character is uppercase or shifted."""
    return character.isupper() or character in '~!@#$%^&*()_{}|:">?'``` 
 
into:

```
def isShiftCharacter(character):
    """Returns True if the key character is uppercase or shifted."""
    return character.isupper() or character in 'shift_map_dict[keyboardlang]'``` 
 
And it *could* be a pretty solid solution for all layouts.

Thoughts?

**Comment by i-need-to-tell-you-something** [comment]
I have the impression (not sure) that this and #137 are the same issue. If that were true, then I think the newer one should be maybe closed and the information from here added there. But I'm not an expert on Github issue management either.

Also getting the keyboard layout in that answer is a Windows-only solution (since the question is about Win10).

**Comment by jarviscodes** [comment]
Just here to clean up this issue as @i-need-to-tell-you-something  suggested given workarounds are plenty and also #137.
