### ISSUE TITLE
Not really useable for MacOs anymore

### ISSUE THREAD

**Issue by eclaassens** [asweigart/pyautogui#418]
Been at it for three days and keep running into bugs.

First thing I tried was move mouse and click...oh click is broken...:
https://github.com/asweigart/pyautogui/issues/417#issuecomment-605598564

Now move to the center of a picture of a button...ah...just found out that retina resolution gives issues:
https://github.com/asweigart/pyautogui/issues/33#issuecomment-353593325

These two bugs make it very difficult to use this library. Could you please look into these @asweigart ? Happy to help testing (Disclaimer: not a seasoned developer...)

**Comment by asweigart** [comment]
I've reverted the recent changes that I made to move from quartz to rubicon. That code needs further testing. It should work now.

**Comment by eclaassens** [comment]
Confirmed. Click works again.
Still the problem with retina screen though...have to divide all coords by 2.

**Comment by kasperschnack** [comment]
Also, it appears that pyautogui.pixel can provide only around 2fps, i think it's because it needs to take a full screenshot in order to do this. It's not [100 ms](https://pyautogui.readthedocs.io/en/latest/screenshot.html) on a mac but closer to 500 ms which unfortunately makes it impossible to use for bot that need to act fast.
