### ISSUE TITLE
possibility to look for multiple images in one screen shot

### ISSUE THREAD

**Issue by Jancs-E** [asweigart/pyautogui#535]
Hi!
currently only function locateAllOnScreen exists, which looks for all instances of single "needle".

If one needs to check for multiple "needles" on the same screen, it means repeating screen capture for as many different needles and required (locateOnScreen) . Would it be possible to fix the screenshot somehow and then look for the "needles"? Or one shuold turn to Pillow for such job?

**Comment by Jancs-E** [comment]
Question solved by using ImageGrab form PIL and cv2.matchTemplate from cv2

**Comment by lsgd** [comment]
Would you mind posting your solution here?
I would be also interested in it

**Comment by Jancs-E** [comment]
solution is quite simple, using the same pyscreeze as pyautogui is using:

`cap_pic = ImageGrab.grab(bbox = None)
for key in pics.keys():
  if key in tmp_team:
    _found = pysceeze.locate(pics[key][1], cap_pic, confidence=0.95, grayscale=True)
    if _found != None:
      do_smth()`

for this specific case I use dict of lists, each list containing other data besides filename of the sub-picture to be looked for.
In other case I pass a list of image filenames to the function responsible for lookup of images. Grayscale in the example was useful for particular case.
In general, I got the idea by reading text of pyautogui

**Comment by lsgd** [comment]
I ended up with another solution. You need to install Pillow, pyautogui and opencv2 via pip.

- I use typing in my code. [Read more](https://docs.python.org/3/library/typing.html#module-typing)
- `match_single()` will **always** return a value for confidence and the x,y coordinates. It's up to you to decide when you assume it's _no match_ anymore. I usually go with everything above 0.95 is a match.
- *location unpacks all elements in location to single values. [Read more](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists)
- It is conventional in Python to use _ for throwaway variables which I do when assigning the values from `cv2.minMaxLoc()`

```
import numpy
import PIL.ImageGrab
import cv2

from typing import Tuple

def grab_screenshot() -> numpy.ndarray:
    image_pil = PIL.ImageGrab.grab()
    image = cv2.cvtColor(numpy.array(image_pil), cv2.COLOR_RGB2BGR)
    return image

def match_single(screenshot: numpy.ndarray, filepath: string) -> Tuple[float, int, int]:
    """Returns the confidence and x,y coordinates for the first match.
    
    Returns:
      Triple consisting of
        - confidence between 0.0 and 1.0
        - X coordinate of the top left corner of the first occurrence of the template in screenshot
        - Y coordinate of the top left corner of the first occurrence of the template in screenshot
    """
    template = cv2.imread(filepath)  # typing: numpy.ndarray
    result = cv2.matchTemplate(screenshot, template.image, cv2.TM_CCOEFF_NORMED)
    _, confidence, _, location = cv2.minMaxLoc(result)
    return confidence, *location
```

**Comment by Jancs-E** [comment]
Yes, I head similar, but then run into problem of how to choose the right algorithm and evaluate results. Then I read pyautogui and pyscreeze sources and decided no to invent the wheel (they anyway rely on cv2)

**Comment by Jancs-E** [comment]
my full code was the follwing:
`a`

**Comment by asweigart** [comment]
The locate functions use the Knuth-Morris-Pratt algorithm to search the pixels for an image, and I don't think there's a way to have them search for multiple things at the same time that would be any faster than searching for multiple things one after the other. I'm going to close this issue, but thanks for giving me some ideas to think about.

**Comment by Raytle** [comment]
@asweigart PyAutoGUI is great! It is in some Python scrips I normally use throughout my workdays. Thank you for creating it and continuing to support it! Please don't take the following as a negative criticism because, well, because it is not. The following is intended to improve PyAutoGUI.

I've been having trouble with `locateCenterOnScreen`. Even when using the optional `region` and `confidence` arguments, sometimes `locateCenterOnScreen` finds a particular image on a particular screen yet other times it fails to find the same particular image on the same particular screen. Of course like most intermittent failures, it is annoying.

Does the approach indicated in the answer to the StackOverflow issue entitled, [Why can't pyautogui locate my image although the code seems to be just fine?](https://stackoverflow.com/a/68308671) seem like it is likely to be a viable approach for obviating the problem? If the following were to seem viable to you, would it be be difficult for you to put a wrapper around it so that a user would be able to easily enter a value for an optional `duration` keyword argument which might have a default value of 1 and which the user could set to, for example, from 1 to 100? 

Personally, I guess I would probably normally set the value for this hypothetical optional `duration` keyword argument to 5 to 10. If I were to enter 5—for example—PyAutoGUI would loop `locateCenterOnScreen` up to 5 times before reporting an error (and ceasing to run).

In case I was unclear, in [Why can't pyautogui locate my image although the code seems to be just fine?](https://stackoverflow.com/a/68308671) I would like you to read the following:

> The image isn't being detected, and consequently it is impossible for python to unpack the variable. Your code only runs the image detection once, and, when trying to automate a GUI process where loading times can vary depending on animations, computer speed, and more, it is generally not a good idea to just detect it once. Also, it isn't 100% reliable, it can take more than a try. I always, when automating a process, use a loop untill [sic] the image is detected. You could make a function like the following:

```
def detect_image(path, duration=0):
    while True:
        image_location = pyautogui.locateCenterOnScreen(path)
        if image_location:
            pyautogui.click(image_location[0], image_location[1], duration=duration)
            break

```

**Comment by lsgd** [comment]
Just for clarification: My goal was not to _find multiple things at the same time_ but to find multiple things without reloading the picture every time.

I am totally fine with just looping over a set of pictures I want to find in the big one.

**Comment by Jancs-E** [comment]
NO, I do not think its possible to do it __simultaneously__
