### ISSUE TITLE
pyautogui is not clicking but is moving to the location.

### ISSUE THREAD

**Issue by sidharthpunathil** [asweigart/pyautogui#575]
pyautogui.moveTo(x, y, 1)
pyautogui.click(x, y, 1)

**Comment by jorg-j** [comment]
Can you provide any more information?
From what I can see here you .moveTo x and y over 1 second
Then are .click at x and y with a single click.

**Comment by sidharthpunathil** [comment]
pyautogui sometimes does not work. It moves to the location but it does not click. 
I had to restart my system to get it to work again.
I am importing pyautogui from a different file (I have doubt if that is the cause). 

Windows 10 Pro

```
    for _ in range(cycle):
        for _ in range(amount):
             pyag.moveTo(us.refresh_x, us.refresh_y, 2)
             pyag.click(us.refresh_x, us.refresh_y, 2)
        time.sleep(intreval)
```

**Comment by sidharthpunathil** [comment]
maybe it's related to multi-threading?

**Comment by jorg-j** [comment]
are you multi threading this code?

**Comment by jorg-j** [comment]
In my experience it is very difficult to accurately troubleshoot issues without details and with information withheld.

I can not replicate your issue in Win 10 Pro based on the information you are providing.

If you are multi threading your code while interacting with a GUI I strongly recommend you revise your methods. 
If you are suggesting the click is not functioning due to a multi threaded process already running on your system then I would suggest it is not the case.
Based on the limited snap shot of information you have provided it is could be a few different things.
1. Are your variables named correctly? `time.sleep(interval)` appears to be spelt incorrectly but if this matches the var name correctly then it's fine
2. Have you read the documentation? As you appear to be duplicating moveTo actions in your click()
3. Is the us.refresh_x and _y variables updated by something? It appears you do a moveTo Click action repeatedly in rapid succession without adjusting these variables AND your sleep timer is in the scope of cycle not amount.

If the code you show above is what is having issues with I would suggest the issue is with your code and not pyautogui as you may be thrashing the mouse driver.

**Comment by sidharthpunathil** [comment]
1. Yes it's actually ok
2. I added the moveTo() because then it at least moves to the location I want to click. 
3. us.refresh_x just gives the x-axis value from an external file. The sleep timer is ok. 

It seems to work when I changed _ to i and j but I don't understand why.

```
   for i in range(cycle):
        for j in range(amount):
             pyag.moveTo(us.refresh_x, us.refresh_y, 2)
             pyag.click(us.refresh_x, us.refresh_y, 2)
        time.sleep(intreval)
```

Thanks for the help! I don't understand why but it works now.

**Comment by jorg-j** [comment]
you're likely incrementing both _ and _ being the same variable name.

please remember to close the issue ;)

**Comment by sidharthpunathil** [comment]
wow, I didn't think about that. thanks :) 
I feel stupid.
