### ISSUE TITLE
Can I help with pyautogui.getWindows() ?

### ISSUE THREAD

**Issue by emilopez** [asweigart/pyautogui#58]
Hi, 

I was looking at Roadmap and I would like to help with the getWindows() method. 

```python
pyautogui.getWindows() # returns a dict of window titles mapped to window IDs
```
Is somebody dealing with that?

Maybe I can help or do a contribution, or, on the other hand,  has someone info or a link to dive into that problem ?

**Comment by asweigart** [comment]
Yes, very much! Currently all these window-related functions are going into the PyGetWindow project, which will then be added to PyAutoGUI. (This is so that people can use these features separately if they don't need everything in PyAutoGUI.) There are other modules which has code to do all this in Windows, however I need to figure out how to do all this in Linux and Mac too so that PyAutoGUI remains cross-platform.

https://github.com/asweigart/PyGetWindow
