### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by nickpythonluajava** [asweigart/pyautogui#597]
I'm trying to make a bot for the Roblox game Funky Friday. It's a rhythm game based off Friday Night Funkin.

<img width="122" alt="fnf" src="https://user-images.githubusercontent.com/78268270/124783900-6b26a700-df13-11eb-9513-a7d493b0fd0a.PNG">

It's not registering all notes, only pressing one note at a time.
Here is my code:

```python
import pyautogui
import pydirectinput

leftColor = (194, 75, 153)
downColor = (0, 255, 255)
upColor = (18, 250, 5)
rightColor = (249, 57, 63)

leftX = 731
#leftY = 189
downX = 888
#downY = 199
upX = 1024
#upY = 191
rightX = 1177
#rightY = 183

y = 189

leftKey = 'left'
downKey = 'down'
upKey = 'up'
rightKey = 'right'

while True:
	if pyautogui.pixelMatchesColor(leftX, y, (leftColor), tolerance = 50): #i also made the tolerance at 80 at one point
		print("LEFT")
		pydirectinput.press(leftKey)
	elif pyautogui.pixelMatchesColor(downX, y, (downColor), tolerance = 50):
		print("DOWN")
		pydirectinput.press(downKey)
	elif pyautogui.pixelMatchesColor(upX, y, (upColor), tolerance = 50):
		print("UP")
		pydirectinput.press(upKey)
	elif pyautogui.pixelMatchesColor(rightX, y, (rightColor), tolerance = 50):
		print("RIGHT")
		pydirectinput.press(rightKey)
```

**Comment by nickpythonluajava** [comment]
Windows 10 x86_64

**Comment by nmstoker** [comment]
As you are using another module (_import pydirectinput_) it looks to me like this isn't directly related to PyAutoGUI and you'd do better to go to the repo for that module or Google it.

However if pydirectinput works like PtAutoGUI's own **press** function then it's expected that it will be pressing them one at a time because the press corresponds to a key up then a key down, so your code effectively let's go of the first key then moves on to the next.

If you want multiple keys at once you need to send the key downs all together and then the key ups all together (for the keys you want pressed at the same time at least)

**Comment by nmstoker** [comment]
@nickpythonluajava I saw you'd also posted this in PyDirectInput:

https://github.com/learncodebygaming/pydirectinput/issues/23

So ideally you should:
1. Close this issue (as I mentioned above it's not relevent to this repo)
2. Answer your own issue using the explanation given here about the order of the down and up keys (ie doing all down keys first and then the up keys) and then when you've written it up, you can close that issue too
Hope the original advice above was useful, I'm pretty sure that the order is your problem.
