### ISSUE TITLE
mouseDown() on Windows causes ctypes.WinError() OSError: [WinError 1813] The specified resource type cannot be found in the image file.

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#77]
I got this bug report:

Hi, I get the following error when trying to use the pyautogui.mouseDown function in Python 3.4 in Windows:

Traceback (most recent call last):File "example.py", line 149, in <module>

create_CR()File "example.py", line 56, in create_CR

pyautogui.mouseDown(703, 248, 'left')File "C:\Python34\lib\site-packages\pyautogui-0.9.33-py3.4.egg\pyautogui\__init__.py", line 274, in mouseDown

platformModule._mouseDown(x, y, 'left')File "C:\Python34\lib\site-packages\pyautogui-0.9.33-py3.4.egg\pyautogui\_pyautogui_win.py", line 393, in _mouseDown

_sendMouseEvent(MOUSEEVENTF_LEFTDOWN, x, y)File "C:\Python34\lib\site-packages\pyautogui-0.9.33-py3.4.egg\pyautogui\_pyautogui_win.py", line 480, in _sendMouseEvent

raise ctypes.WinError() OSError: [WinError 1813] The specified resource type cannot be found in the image file.

Any ideas? Thank you!

**Comment by VolkerH** [comment]
I receive a similar error message (same code lines) when trying to use dragRel on Windows7 64bit, Python 2.7 (Anaconda) - pyautogui installed via pip today.
I see the issue is closed, but I don't see how it was resolved.

In [39]: pyautogui.dragRel(None,-100, duration=2)
---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
<ipython-input-39-9ca853eb04e0> in <module>()
----> 1 pyautogui.dragRel(None,-100, duration=2)

C:\Anaconda2\lib\site-packages\pyautogui\__init__.pyc in dragRel(xOffset, yOffse
t, duration, tween, button, pause, _pause)
    729
    730     mousex, mousey = platformModule._position()
--> 731     mouseDown(button=button, _pause=False)
    732     _mouseMoveDrag('drag', mousex, mousey, xOffset, yOffset, duration, t
ween, button)
    733     mouseUp(button=button, _pause=False)

C:\Anaconda2\lib\site-packages\pyautogui\__init__.pyc in mouseDown(x, y, button,
 duration, tween, pause, _pause)
    272     x, y = platformModule._position() # TODO - this isn't right. We need
 to check the params.
    273     if button == 1 or str(button).lower() == 'left':
--> 274         platformModule._mouseDown(x, y, 'left')
    275     elif button == 2 or str(button).lower() == 'middle':
    276         platformModule._mouseDown(x, y, 'middle')

C:\Anaconda2\lib\site-packages\pyautogui\_pyautogui_win.pyc in _mouseDown(x, y,
button)
    391     """
    392     if button == 'left':
--> 393         _sendMouseEvent(MOUSEEVENTF_LEFTDOWN, x, y)
    394     elif button == 'middle':
    395         _sendMouseEvent(MOUSEEVENTF_MIDDLEDOWN, x, y)

C:\Anaconda2\lib\site-packages\pyautogui\_pyautogui_win.pyc in _sendMouseEvent(e
v, x, y, dwData)
    478
    479     if ctypes.windll.kernel32.GetLastError() != 0:
--> 480         raise ctypes.WinError()
    481
    482

WindowsError: [Error 123] The filename, directory name, or volume label syntax i
s incorrect.
